name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image and Push to DockerHub
      run: docker buildx build \
        --platform=linux/amd64,linux/arm64 \
        --output "type=image,push=true" \
        --file ./Dockerfile . \
        --tag jscblack/yaded:$(date +%s) \
